---

version: "2.4"
services:
  neofs_coredns:
    image: ${COREDNS_IMAGE}:${COREDNS_VERSION}
    container_name: coredns
    domainname: ${LOCAL_DOMAIN}
    hostname: coredns
    restart: "no"
    networks:
      coredns:
      internet:
        ipv4_address: ${IPV4_PREFIX}.53
    stop_signal: SIGKILL
    volumes:
      - ./Corefile:/Corefile
      - ./../../vendor/hosts:/etc/hosts

networks:
  coredns:
  internet:
    external: true
    name: basenet_internet
